spring:
  application:
    name: trip_coupon

  # datasource setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripcoupon?serverTimezone=UTC
    username: ssafy
    password: ssafy

  data:
    redis:
      host: localhost
      port: 6379


# myBatis config setting
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ssafy.trip_coupon.domain.**.entity

jwt:
  salt: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  access-expire-time: 3600000
  refresh-expire-time: 108000000