global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]

  - job_name: 'mysqld_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9104' ]